analyze_activity:
  description: |
    Analyze the first 10 posts from the user's LinkedIn profile to determine their activity level.
    You will receive a JSON array of posts which includes posting dates.
    
    Based on frequency and recency of posts, assign an activity score from 1-10, where:
    - 1-3: Low activity (infrequent posting, long gaps between posts)
    - 4-7: Medium activity (moderate posting, some consistency)
    - 8-10: High activity (frequent posting, high consistency)
    
    Posts JSON: {post_times}
    
    Don't explain your reasoning - just return a single integer between 1-10.
  expected_output: Integer between 1-10
  agent: activity_analyser

summarize_profile:
  description: |
    Create a professional summary based on the user's LinkedIn profile data.
    
    Use the following information to create a 3-4 sentence professional summary:
    - Summary: {summary}
    - Education: {educations_data}
    - Positions: {positions_data}
    - Skills: {skills_data}
    - Headline: {headline}
    
    Focus on the person's professional identity, expertise, experience, and unique value.
    Return only the summary text with no explanations.
  expected_output: 3-4 sentence professional summary  
  agent: profile_summarizer

analyze_content:
  description: |
    Analyze the content of the first 10 posts from the user's LinkedIn profile.
    Posts are provided as a JSON array: {posts_data}
    
    Identify:
    1. Main topics/themes discussed
    2. Professional interests indicated
    3. Technologies, industries, or skills mentioned
    
    Write a short paragraph (3-5 sentences) summarizing what the content reveals about
    the user's professional focus and interests. Return only the summary text.
  expected_output: Short paragraph summarizing content focus
  agent: content_analyst


assess_alignment:
  description: |
    Evaluate the user's potential based on the specific type of analysis to be done ({analyse}).
    
    Consider the user's profile data:
    - Posts: {posts_data}
    - Summary: {summary}
    - Education: {educations_data}
    - Headline: {headline}
    - Positions: {positions_data}
    - Skills: {skills_data}
    - HiDevs vision: {hidevs_vision}
    
    Provide a score between 1-10 where 10 indicates very strong potential for the requested analysis type. 
    Include a 2-3 sentence justification.

    Format your response as: "X - explanation"
  expected_output: Score (1-10) and short explanation
  agent: strategic_analyzer